package app.gui.inicio;

import app.dataStruct.ListaPacientes;
import app.logic.Fecha;
import app.logic.users.Paciente;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class buscarPacientePanel extends javax.swing.JPanel {

    private final Fecha actual;
    // Atributo de lista
    private static ListaPacientes listaPacientes;
    private DefaultTableModel model;
    private Paciente pacienteActual;

    // Modelo lista
    private DefaultListModel dlm = new DefaultListModel();

    /**
     * Creates new form inicioPanel
     *
     * @param usuario
     */
    public buscarPacientePanel() {
        initComponents();
        actual = new Fecha();
        pacienteActual = null;
        actualizarFecha(actual);
        setInformation();
        lstResultados.setModel(dlm);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        fechaLabel = new javax.swing.JLabel();
        bienvenidaLabel = new javax.swing.JLabel();
        edadLabel = new javax.swing.JLabel();
        filtrarBOX = new javax.swing.JComboBox<>();
        buscarButton = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        todosBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstResultados = new javax.swing.JList<>();
        cedulaTxt = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        buscarPacienteButton = new javax.swing.JButton();
        nombreLabel = new javax.swing.JLabel();
        apellidoLabel = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(18, 84, 136));
        jPanel1.setForeground(new java.awt.Color(255, 153, 153));

        fechaLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        fechaLabel.setForeground(new java.awt.Color(255, 255, 255));
        fechaLabel.setText("El día de hoy es -- de -- del año --");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(fechaLabel)
                .addContainerGap(468, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(fechaLabel)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 870, -1));

        bienvenidaLabel.setFont(new java.awt.Font("Roboto", 1, 48)); // NOI18N
        bienvenidaLabel.setForeground(new java.awt.Color(102, 0, 153));
        bienvenidaLabel.setText("Resultados");
        add(bienvenidaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, -1, -1));

        edadLabel.setFont(new java.awt.Font("Roboto", 1, 28)); // NOI18N
        edadLabel.setForeground(new java.awt.Color(51, 51, 51));
        edadLabel.setText("Filtrar resultados");
        add(edadLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 540, -1, 40));

        filtrarBOX.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "Leve", "Moderada", "Hoy", "Suma Resta", "Comprensión", "Memoria", "Identificar Letras", "Reconocer sonido", "Identificar colores" }));
        add(filtrarBOX, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 540, 210, -1));

        buscarButton.setBackground(new java.awt.Color(18, 84, 136));
        buscarButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        buscarButton.setForeground(new java.awt.Color(0, 0, 0));
        buscarButton.setText("Buscar");
        buscarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarButtonActionPerformed(evt);
            }
        });
        add(buscarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 330, 130, -1));

        jSeparator2.setBackground(new java.awt.Color(81, 3, 23));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 570, 20));

        todosBtn.setBackground(new java.awt.Color(18, 84, 136));
        todosBtn.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        todosBtn.setForeground(new java.awt.Color(255, 255, 255));
        todosBtn.setText("Mostrar todos");
        todosBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        todosBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                todosBtnActionPerformed(evt);
            }
        });
        add(todosBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 550, 220, 30));

        lstResultados.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(lstResultados);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 630, 750, 130));

        cedulaTxt.setBackground(new java.awt.Color(102, 102, 102));
        cedulaTxt.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        cedulaTxt.setForeground(new java.awt.Color(255, 255, 255));
        cedulaTxt.setText("0605226992");
        cedulaTxt.setBorder(null);
        cedulaTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        cedulaTxt.setOpaque(true);
        cedulaTxt.setSelectedTextColor(new java.awt.Color(153, 153, 153));
        cedulaTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cedulaTxtActionPerformed(evt);
            }
        });
        add(cedulaTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 190, 130, 40));

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 230, 130, 10));

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 51, 51));
        jLabel9.setText("Ingrese la cédula del paciente a buscar");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, -1, -1));

        buscarPacienteButton.setBackground(new java.awt.Color(18, 84, 136));
        buscarPacienteButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        buscarPacienteButton.setForeground(new java.awt.Color(0, 0, 0));
        buscarPacienteButton.setText("Mostrar todos");
        buscarPacienteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarPacienteButtonActionPerformed(evt);
            }
        });
        add(buscarPacienteButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 190, 200, 40));

        nombreLabel.setFont(new java.awt.Font("Roboto", 1, 22)); // NOI18N
        nombreLabel.setForeground(new java.awt.Color(51, 51, 51));
        nombreLabel.setText("nombre");
        add(nombreLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 300, -1, -1));

        apellidoLabel.setFont(new java.awt.Font("Roboto", 1, 22)); // NOI18N
        apellidoLabel.setForeground(new java.awt.Color(51, 51, 51));
        apellidoLabel.setText("apellido");
        add(apellidoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 340, -1, -1));

        fondo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        fondo.setForeground(new java.awt.Color(51, 51, 51));
        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/backgroundMain.jpg"))); // NOI18N
        add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 800));
    }// </editor-fold>//GEN-END:initComponents

    private void buscarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarButtonActionPerformed
        // Saca el objeto seleccionado del menu desplegable y lo almacena como String en filtro
        String filtro = filtrarBOX.getSelectedItem().toString();

        // Limpia los contenidos de la tabla
        model.setRowCount(0);

        // Invoca a la funcion buscarResultadoActividad en usuario enviando el filtro por el cual quiero buscar
        // Como resultado obtiene una lista de ResultadoActividad el cual se almacena en listaResultados
        //List<ResultadoActividad> listaResultados = usuario.buscarResultadoActividad(filtro);
        // se recorre la lista de resultados e inserta los valores en la tabla fila por fila
        //listaResultados.forEach(resultadoActividad -> {
        //model.addRow(new Object[]{resultadoActividad.getNombre(), resultadoActividad.getEtapa(), resultadoActividad.getAciertos(), resultadoActividad.getSegundos(), resultadoActividad.getFecha().getDia(), resultadoActividad.getFecha().getMesString()});
        //});
    }//GEN-LAST:event_buscarButtonActionPerformed

    private void todosBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_todosBtnActionPerformed
        actualizarListaPacientes();
    }//GEN-LAST:event_todosBtnActionPerformed

    private void cedulaTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cedulaTxtActionPerformed

    }//GEN-LAST:event_cedulaTxtActionPerformed

    private void buscarPacienteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarPacienteButtonActionPerformed
        listaPacientes = MainScreen.getListaPacientes();
        System.out.println(listaPacientes.tamanio());

        String cedula = cedulaTxt.getText();
        this.pacienteActual = buscarPaciente(cedula);
        if (pacienteActual != null) {
            actualizarListaPacientes();
            nombreLabel.setText("Nombre: " + pacienteActual.getNombre());
            apellidoLabel.setText("Apellido: " + pacienteActual.getApellido());
        } else {
            JOptionPane.showMessageDialog(null, "No encontrado");
        }

    }//GEN-LAST:event_buscarPacienteButtonActionPerformed

    public void setUsuario(ListaPacientes usuarioListaPacientes) {
        this.listaPacientes = listaPacientes;
    }

    public void actualizarListaPacientes() {
        listaPacientes = MainScreen.getListaPacientes();

        dlm.removeAllElements();
        listaPacientes.getPacientes().forEach(paciente -> {
            dlm.addElement(paciente.toString());
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel apellidoLabel;
    private javax.swing.JLabel bienvenidaLabel;
    private javax.swing.JButton buscarButton;
    private javax.swing.JButton buscarPacienteButton;
    private javax.swing.JTextField cedulaTxt;
    private javax.swing.JLabel edadLabel;
    private javax.swing.JLabel fechaLabel;
    private javax.swing.JComboBox<String> filtrarBOX;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JList<String> lstResultados;
    private javax.swing.JLabel nombreLabel;
    private javax.swing.JButton todosBtn;
    // End of variables declaration//GEN-END:variables

    private void actualizarFecha(Fecha actual) {
        fechaLabel.setText("Hoy es " + actual.getDia() + " de " + actual.getMesString() + " del año " + actual.getAnio() + " ");
    }

    public void setInformation() {

    }

    private Paciente buscarPaciente(String cedula) {
        dlm.removeAllElements();

        for (Paciente paciente : listaPacientes.getPacientes()) {
            if (paciente.getCedula().equals(cedula)) {
                dlm.addElement(paciente.toString());
                return paciente;
            }
        }
        return null;

    }
}
