package app.gui.inicio;

import app.logic.Fecha;
import app.logic.users.Administrador;
import app.logic.users.Usuario;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 * Programa BrainUP InicioPanel permite entrar y registrar
 *
 * @author Valverde, Vinueza, Vintimilla
 */
public class InicioPanel extends javax.swing.JPanel {

    private Usuario usuario;

    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

    /**
     * Creates new form inicioPanel
     *
     * @param usuario
     */
    public InicioPanel(Usuario usuario) {
        initComponents();
        // Invoca al método actualizarFecha enviando un objeto de fecha actual para actualizar el label fecha con la fecha actual 
        this.usuario = usuario;
        // Método el cual muestra la información el usuairo en los labels del panel
        setInformation();
        adminTxt.setVisible(false);

        // Si la etapa es 2(avanzada) entonces se muestra un mensaje
        if (usuario.getRol().equals("Administrador")) {
            adminTxt.setVisible(true);
            msg2.setText("TODO");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        bienvenidaLabel = new javax.swing.JLabel();
        text1Label = new javax.swing.JLabel();
        nombreLabel = new javax.swing.JLabel();
        apellidoLabel = new javax.swing.JLabel();
        fechaNacLabel = new javax.swing.JLabel();
        edadLabel = new javax.swing.JLabel();
        adminTxt = new javax.swing.JLabel();
        msg2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        avatarLogo = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(870, 800));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bienvenidaLabel.setFont(new java.awt.Font("Roboto", 1, 30)); // NOI18N
        bienvenidaLabel.setForeground(new java.awt.Color(102, 0, 153));
        bienvenidaLabel.setText("Bienvenido :)");
        bg.add(bienvenidaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, -1, -1));

        text1Label.setFont(new java.awt.Font("Roboto", 1, 28)); // NOI18N
        text1Label.setForeground(new java.awt.Color(0, 51, 204));
        text1Label.setText("Perfil");
        text1Label.setToolTipText("");
        bg.add(text1Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        nombreLabel.setFont(new java.awt.Font("Roboto", 1, 22)); // NOI18N
        nombreLabel.setForeground(new java.awt.Color(51, 51, 51));
        bg.add(nombreLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, -1, -1));

        apellidoLabel.setFont(new java.awt.Font("Roboto", 1, 22)); // NOI18N
        apellidoLabel.setForeground(new java.awt.Color(51, 51, 51));
        bg.add(apellidoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 260, -1, -1));

        fechaNacLabel.setFont(new java.awt.Font("Roboto", 1, 22)); // NOI18N
        fechaNacLabel.setForeground(new java.awt.Color(51, 51, 51));
        bg.add(fechaNacLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, -1, -1));

        edadLabel.setFont(new java.awt.Font("Roboto", 1, 22)); // NOI18N
        edadLabel.setForeground(new java.awt.Color(51, 51, 51));
        bg.add(edadLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, -1, -1));

        adminTxt.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        adminTxt.setForeground(new java.awt.Color(51, 0, 102));
        adminTxt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/corporate_profile.png"))); // NOI18N
        bg.add(adminTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 100, 440, 520));

        msg2.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        msg2.setForeground(new java.awt.Color(0, 0, 102));
        bg.add(msg2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 80, 30));

        jSeparator1.setBackground(new java.awt.Color(81, 3, 23));
        bg.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 750, 20));
        bg.add(avatarLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 70, 70));

        fondo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        fondo.setForeground(new java.awt.Color(51, 51, 51));
        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/backgroundMain.jpg"))); // NOI18N
        bg.add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 610));

        add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel adminTxt;
    private javax.swing.JLabel apellidoLabel;
    private javax.swing.JLabel avatarLogo;
    private javax.swing.JPanel bg;
    private javax.swing.JLabel bienvenidaLabel;
    private javax.swing.JLabel edadLabel;
    private javax.swing.JLabel fechaNacLabel;
    private javax.swing.JLabel fondo;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel msg2;
    private javax.swing.JLabel nombreLabel;
    private javax.swing.JLabel text1Label;
    // End of variables declaration//GEN-END:variables



    public void setInformation() {
        // Intenta obtener el nombre
        try {
            String saludo = "Hola";
            if (usuario.getSexo().equals("Femenino")) {
                saludo = "Bienvenida Dra. ";
            } else {
                saludo = "Bienvenido Dr. ";
            }

            if (usuario instanceof Administrador) {
                saludo = "Consola Administrativa - ";
                text1Label.setText("Dashboard");
            }
            bienvenidaLabel.setText(saludo + usuario.getNombre());
        } catch (NullPointerException npe) {
            bienvenidaLabel.setText("Hola  usuario");
        } catch (Exception e) {
            bienvenidaLabel.setText("Problema al encontrar usuario");
        }
        // Llena los datos de usuario en los labels
        if (usuario.getRol().equals("Medico")) {
            try {
                text1Label.setText("Perfil médico");
                nombreLabel.setText("Nombre " + usuario.getNombre());
                apellidoLabel.setText("Apellido " + usuario.getApellido());
                // Direccion del avatar
                String direccion = "/imagen/icon/avatar/avatar" + usuario.getAvatar() + ".png";
                // Crea un objeto de icono 
                Icon icono = new ImageIcon(getClass().getResource(direccion));
                // Actializa el icono
                avatarLogo.setIcon(icono);
                fechaNacLabel.setText("Nacimiento" + usuario.getFechaNacimientoString());
                // TODO
                edadLabel.setText("Edad" + usuario.getEdad() + " años");
            } catch (NullPointerException npe) {
                bienvenidaLabel.setText("Problema al encontrar usuario");
            } catch (Exception ex) {
                System.out.println("Error en InicioPanel al leer los datos del usuario");
            }
        }
    }

}
