package app.gui.inicio;

import app.dataStruct.ListaPacientes;
import app.logic.Main;
import app.logic.users.Usuario;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import org.netbeans.lib.awtextra.AbsoluteConstraints;

public final class MainScreen extends javax.swing.JFrame {

    public static Usuario usuario;
    public static String userID;
    public static ListaPacientes listaPacientes;
    // Paneles
    private app.gui.inicio.InicioPanel pInicio = null;
    private buscarPacientePanel pResultados = null;
    private ConfigPanel pConfig = null;
    private AyudaPanel pAyuda = null;
    private registroMedicoPanel pRegistrarMedico = null;
    private buscarMedicoPanel pBuscarMedico = null;
    private registroPacientePanel pRegistrarPaciente = null;

    private MainScreen() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    public Usuario getUsuario() {
        return usuario;
    }

    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

    public static ListaPacientes getListaPacientes() {
        return listaPacientes;
    }

    public static void setListaPacientes(ListaPacientes listaPacientes) {
        MainScreen.listaPacientes = listaPacientes;
    }
    
    

    /**
     * Creates new form MainScreen
     *
     * @param usuario
     */
    public MainScreen(Usuario usuario) {
        MainScreen.usuario = usuario;
        MainScreen.listaPacientes = Main.obtenerPacientesDataBase();
        initComponents();
        // Por defecto
        registrarMedicoButton.setVisible(false);
        buscarMedicoButton.setVisible(false);

        // Si la el rol es administrador entonces se muestran más opciones
        if (usuario.getRol().equals("Administrador")) {
            registrarMedicoButton.setVisible(true);
            buscarMedicoButton.setVisible(true);
            content.setBackground(new java.awt.Color(245, 245, 245));
        }

        // Inicializa los paneles
        inicializarPaneles(usuario);

        //setInformation();
        this.setVisible(true);
        showPanel(pInicio);
        MainScreen.userID = usuario.getCedula();

        // Obtiene la lista de Resultados de actividades y la asigna al usuario
        //usuario.setListaResultado(Main.obtenerResultadoActividadDataBase(usuario.getCedula()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        content = new javax.swing.JPanel();
        iconImg = new javax.swing.JLabel();
        buscarMedicoButton = new javax.swing.JButton();
        registrarMedicoButton = new javax.swing.JButton();
        helpButton = new javax.swing.JButton();
        homeButton1 = new javax.swing.JButton();
        recButton = new javax.swing.JButton();
        statsButton = new javax.swing.JButton();
        configButton = new javax.swing.JButton();
        contenido = new javax.swing.JPanel();
        salirButton = new javax.swing.JButton();
        logoutButton = new javax.swing.JButton();
        registrarPacienteButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BrainUP");
        setResizable(false);

        content.setBackground(new java.awt.Color(18, 84, 136));
        content.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        iconImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/icon/home_house.png"))); // NOI18N
        content.add(iconImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 100, 90));

        buscarMedicoButton.setBackground(new java.awt.Color(0, 204, 204));
        buscarMedicoButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        buscarMedicoButton.setForeground(new java.awt.Color(51, 51, 51));
        buscarMedicoButton.setText("Buscar Médico");
        buscarMedicoButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        buscarMedicoButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buscarMedicoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarMedicoButtonActionPerformed(evt);
            }
        });
        content.add(buscarMedicoButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 500, 240, 50));

        registrarMedicoButton.setBackground(new java.awt.Color(0, 204, 204));
        registrarMedicoButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        registrarMedicoButton.setForeground(new java.awt.Color(51, 51, 51));
        registrarMedicoButton.setText("Registrar Médico");
        registrarMedicoButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        registrarMedicoButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        registrarMedicoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarMedicoButtonActionPerformed(evt);
            }
        });
        content.add(registrarMedicoButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 440, 240, 50));

        helpButton.setBackground(new java.awt.Color(173, 217, 216));
        helpButton.setForeground(new java.awt.Color(51, 51, 51));
        helpButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/icon/chat_sms.png"))); // NOI18N
        helpButton.setText("Ayuda");
        helpButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        helpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpButtonActionPerformed(evt);
            }
        });
        content.add(helpButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 650, 240, 40));

        homeButton1.setBackground(new java.awt.Color(42, 147, 213));
        homeButton1.setFont(new java.awt.Font("Montserrat", 1, 25)); // NOI18N
        homeButton1.setForeground(new java.awt.Color(255, 255, 255));
        homeButton1.setText("Inicio");
        homeButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        homeButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        homeButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButton1ActionPerformed(evt);
            }
        });
        content.add(homeButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 130, 240, 60));

        recButton.setBackground(new java.awt.Color(55, 202, 236));
        recButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        recButton.setForeground(new java.awt.Color(51, 51, 51));
        recButton.setText("Recomendaciones");
        recButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        recButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        recButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recButtonActionPerformed(evt);
            }
        });
        content.add(recButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 320, 240, 50));

        statsButton.setBackground(new java.awt.Color(55, 202, 236));
        statsButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        statsButton.setForeground(new java.awt.Color(51, 51, 51));
        statsButton.setText("Buscar Paciente");
        statsButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        statsButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        statsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statsButtonActionPerformed(evt);
            }
        });
        content.add(statsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 260, 240, 50));

        configButton.setBackground(new java.awt.Color(55, 202, 236));
        configButton.setForeground(new java.awt.Color(51, 51, 51));
        configButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/icon/settings_cog_gear_1.png"))); // NOI18N
        configButton.setText("Configurar");
        configButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        configButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                configButtonActionPerformed(evt);
            }
        });
        content.add(configButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 590, 240, 40));

        javax.swing.GroupLayout contenidoLayout = new javax.swing.GroupLayout(contenido);
        contenido.setLayout(contenidoLayout);
        contenidoLayout.setHorizontalGroup(
            contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 870, Short.MAX_VALUE)
        );
        contenidoLayout.setVerticalGroup(
            contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );

        content.add(contenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 870, 800));

        salirButton.setBackground(new java.awt.Color(255, 102, 102));
        salirButton.setForeground(new java.awt.Color(51, 51, 51));
        salirButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/icon/settings_cog_gear_1.png"))); // NOI18N
        salirButton.setText("Salir");
        salirButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        salirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirButtonActionPerformed(evt);
            }
        });
        content.add(salirButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 760, 240, 30));

        logoutButton.setBackground(new java.awt.Color(255, 102, 102));
        logoutButton.setForeground(new java.awt.Color(51, 51, 51));
        logoutButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/icon/settings_cog_gear_1.png"))); // NOI18N
        logoutButton.setText("Cerrar sesión");
        logoutButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });
        content.add(logoutButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 710, 240, 40));

        registrarPacienteButton.setBackground(new java.awt.Color(55, 202, 236));
        registrarPacienteButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        registrarPacienteButton.setForeground(new java.awt.Color(51, 51, 51));
        registrarPacienteButton.setText("Registrar Paciente");
        registrarPacienteButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        registrarPacienteButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        registrarPacienteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarPacienteButtonActionPerformed(evt);
            }
        });
        content.add(registrarPacienteButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 200, 240, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(content, javax.swing.GroupLayout.PREFERRED_SIZE, 1100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(content, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void configButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_configButtonActionPerformed
        Icon icono = new ImageIcon(getClass().getResource("/imagen/icon/settings_cog_gear.png"));
        iconImg.setIcon(icono);
        colorButtons();
        showPanel(pConfig);
    }//GEN-LAST:event_configButtonActionPerformed

    private void recButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recButtonActionPerformed
        Icon icono = new ImageIcon(getClass().getResource("/imagen/icon/news_paper.png"));
        iconImg.setIcon(icono);
        colorButtons();
        recButton.setBackground(new java.awt.Color(42, 147, 213));
        // TODO
        showPanel(pAyuda);
    }//GEN-LAST:event_recButtonActionPerformed

    private void homeButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeButton1ActionPerformed

        showPanel(pInicio);
        colorButtons();
        pInicio.setInformation();
        homeButton1.setBackground(new java.awt.Color(42, 147, 213));
        Icon icono = new ImageIcon(getClass().getResource("/imagen/icon/home_house.png"));
        iconImg.setIcon(icono);
    }//GEN-LAST:event_homeButton1ActionPerformed

    private void helpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpButtonActionPerformed
        Icon icono = new ImageIcon(getClass().getResource("/imagen/icon/puzzle_component.png"));
        iconImg.setIcon(icono);
        colorButtons();
        showPanel(pAyuda);
    }//GEN-LAST:event_helpButtonActionPerformed

    private void registrarMedicoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarMedicoButtonActionPerformed
        Icon icono = new ImageIcon(getClass().getResource("/imagen/icon/puzzle_component.png"));
        iconImg.setIcon(icono);
        colorButtons();
        registrarMedicoButton.setBackground(new java.awt.Color(42, 147, 213));
        // TODO
        showPanel(pRegistrarMedico);

    }//GEN-LAST:event_registrarMedicoButtonActionPerformed

    private void statsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statsButtonActionPerformed
        Icon icono = new ImageIcon(getClass().getResource("/imagen/icon/cup_reward.png"));
        iconImg.setIcon(icono);
        colorButtons();
        statsButton.setBackground(new java.awt.Color(42, 147, 213));
        showPanel(pResultados);
    }//GEN-LAST:event_statsButtonActionPerformed

    private void registrarPacienteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarPacienteButtonActionPerformed
        Icon icono = new ImageIcon(getClass().getResource("/imagen/icon/cup_reward.png"));
        iconImg.setIcon(icono);
        colorButtons();
        registrarPacienteButton.setBackground(new java.awt.Color(42, 147, 213));
        showPanel(pRegistrarPaciente);
    }//GEN-LAST:event_registrarPacienteButtonActionPerformed

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        this.dispose();
        // Inicia el programa mostrando el inicio
        InicioForm mainInicio = new InicioForm();
        mainInicio.setVisible(true);
        mainInicio.setLocationRelativeTo(null);
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void buscarMedicoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarMedicoButtonActionPerformed
        Icon icono = new ImageIcon(getClass().getResource("/imagen/icon/cup_reward.png"));
        iconImg.setIcon(icono);
        colorButtons();
        buscarMedicoButton.setBackground(new java.awt.Color(42, 147, 213));
        showPanel(pBuscarMedico);
    }//GEN-LAST:event_buscarMedicoButtonActionPerformed

    private void salirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_salirButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new MainScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscarMedicoButton;
    private javax.swing.JButton configButton;
    private javax.swing.JPanel contenido;
    private javax.swing.JPanel content;
    private javax.swing.JButton helpButton;
    private javax.swing.JButton homeButton1;
    private javax.swing.JLabel iconImg;
    private javax.swing.JButton logoutButton;
    private javax.swing.JButton recButton;
    private javax.swing.JButton registrarMedicoButton;
    private javax.swing.JButton registrarPacienteButton;
    private javax.swing.JButton salirButton;
    private javax.swing.JButton statsButton;
    // End of variables declaration//GEN-END:variables

    /**
     * Recibe el panel para cabiarlo en el panel contenido
     *
     * @param p panel
     */
    private void showPanel(JPanel p) {
        p.setSize(870, 800);
        contenido.removeAll();
        contenido.add(p, new AbsoluteConstraints(0, 0, -1, -1));
        contenido.revalidate();
        contenido.repaint();
    }

    /**
     * Inicializa los paneles
     *
     * @param usuario
     */
    private void inicializarPaneles(Usuario usuario) {
        pInicio = new InicioPanel(usuario);

        pConfig = new ConfigPanel(usuario);
        pAyuda = new AyudaPanel();
        pRegistrarMedico = new registroMedicoPanel(usuario);
        pRegistrarPaciente = new registroPacientePanel();
        pBuscarMedico = new buscarMedicoPanel(usuario);
        pResultados = new buscarPacientePanel();

        pInicio.setUsuario(usuario);
        pConfig.setUsuario(usuario);
    }

    private void colorButtons() {
        homeButton1.setBackground(new java.awt.Color(55, 202, 236));
        registrarMedicoButton.setBackground(new java.awt.Color(0, 204, 204));
        buscarMedicoButton.setBackground(new java.awt.Color(0, 204, 204));
        recButton.setBackground(new java.awt.Color(55, 202, 236));
        statsButton.setBackground(new java.awt.Color(55, 202, 236));
        registrarPacienteButton.setBackground(new java.awt.Color(55, 202, 236));
        configButton.setBackground(new java.awt.Color(55, 202, 236));
    }
}
