package app.gui.inicio;

import app.dataStruct.ListaPacientes;
import app.logic.Main;
import app.logic.SignosVitalesFormulario;
import app.logic.users.Paciente;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

public class SignosVitales extends javax.swing.JPanel {

    // Atributo de lista
    private static ListaPacientes listaPacientes;
    private Paciente pacienteActual;
    public static ArrayList<SignosVitalesFormulario> listaSignosVitales;
    public static ArrayList<SignosVitalesFormulario> listaSignosVitalesPaciente;

    // Modelo lista
    private DefaultListModel dlm = new DefaultListModel();

    /**
     * Creates new form inicioPanel
     *
     * @param usuario
     */
    public SignosVitales() {
        initComponents();
        pacienteActual = null;
        setInformation();
        registrarSignosVButton.setVisible(false);
        lstFormularios.setModel(dlm);
        listaSignosVitales = obtenerFormulariosRegistrados();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cedulaTxt = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        buscarPacienteButton = new javax.swing.JButton();
        nombreLabel = new javax.swing.JLabel();
        apellidoLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        registrarSignosVButton = new javax.swing.JButton();
        tituloLabel = new javax.swing.JLabel();
        jSeparator10 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstFormularios = new javax.swing.JList<>();
        fondo = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cedulaTxt.setBackground(new java.awt.Color(102, 102, 102));
        cedulaTxt.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        cedulaTxt.setForeground(new java.awt.Color(255, 255, 255));
        cedulaTxt.setText("0605226992");
        cedulaTxt.setBorder(null);
        cedulaTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        cedulaTxt.setOpaque(true);
        cedulaTxt.setSelectedTextColor(new java.awt.Color(153, 153, 153));
        cedulaTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cedulaTxtActionPerformed(evt);
            }
        });
        add(cedulaTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 80, 140, 30));

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 110, 140, 10));

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 51, 51));
        jLabel9.setText("Ingrese la cédula del paciente");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, -1));

        buscarPacienteButton.setBackground(new java.awt.Color(18, 84, 136));
        buscarPacienteButton.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        buscarPacienteButton.setForeground(new java.awt.Color(255, 255, 255));
        buscarPacienteButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/icon/search_1.png"))); // NOI18N
        buscarPacienteButton.setText("Buscar Paciente");
        buscarPacienteButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        buscarPacienteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarPacienteButtonActionPerformed(evt);
            }
        });
        add(buscarPacienteButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 80, 200, -1));

        nombreLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        nombreLabel.setForeground(new java.awt.Color(51, 51, 51));
        nombreLabel.setText("nombre");
        add(nombreLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, -1, -1));

        apellidoLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        apellidoLabel.setForeground(new java.awt.Color(51, 51, 51));
        apellidoLabel.setText("apellido");
        add(apellidoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 160, -1, -1));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Encontrado:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, -1));

        registrarSignosVButton.setBackground(new java.awt.Color(0, 204, 204));
        registrarSignosVButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        registrarSignosVButton.setForeground(new java.awt.Color(0, 0, 0));
        registrarSignosVButton.setText("Registrar Signos Vitales");
        registrarSignosVButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarSignosVButtonActionPerformed(evt);
            }
        });
        add(registrarSignosVButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, 290, 60));

        tituloLabel.setFont(new java.awt.Font("Roboto", 1, 30)); // NOI18N
        tituloLabel.setForeground(new java.awt.Color(102, 0, 153));
        tituloLabel.setText("Signos Vitales");
        add(tituloLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        jSeparator10.setBackground(new java.awt.Color(81, 3, 23));
        add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 760, 20));

        lstFormularios.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        lstFormularios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstFormulariosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(lstFormularios);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, 660, 180));

        fondo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        fondo.setForeground(new java.awt.Color(51, 51, 51));
        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/backgroundMain.jpg"))); // NOI18N
        add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));
    }// </editor-fold>//GEN-END:initComponents

    private void cedulaTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cedulaTxtActionPerformed

    }//GEN-LAST:event_cedulaTxtActionPerformed

    private void buscarPacienteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarPacienteButtonActionPerformed
        String cedula = cedulaTxt.getText();
        
        actualizarPacienteActual(cedula);
        //vaciarCampos();
        // Si se ha encontrado un paciente, entonces 
        if (pacienteActual != null) {
            listaSignosVitalesPaciente = null;
            
            listaSignosVitalesPaciente = filtrarFormularios(cedula);
            actualizarListaFormularios();

            // Muestra los botones
            registrarSignosVButton.setVisible(true);
        } else {
            registrarSignosVButton.setVisible(false);
        }
    }//GEN-LAST:event_buscarPacienteButtonActionPerformed
    
    private void vaciarCampos() {
        cedulaTxt.setText("");
        
    }

    private void registrarSignosVButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarSignosVButtonActionPerformed
        filtrarFormularios(cedulaTxt.getText());
        int id = listaSignosVitalesPaciente.size();
        System.out.println(id);
        TriajeGui triajeGui = new TriajeGui(pacienteActual, id);
        triajeGui.setVisible(true);
    }//GEN-LAST:event_registrarSignosVButtonActionPerformed

    private void lstFormulariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstFormulariosMouseClicked
        String idSeleccion = lstFormularios.getSelectedValue().substring(0, lstFormularios.getSelectedValue().indexOf(" "));
        System.out.println(idSeleccion);
        
        TriajeGuiForm ventanaTriaje = new TriajeGuiForm(pacienteActual, listaSignosVitalesPaciente.get(Integer.parseInt(idSeleccion)));
        ventanaTriaje.setVisible(true);

    }//GEN-LAST:event_lstFormulariosMouseClicked
    
    public void setUsuario(ListaPacientes usuarioListaPacientes) {
        SignosVitales.listaPacientes = usuarioListaPacientes;
    }
    
    public void actualizarListaFormularios() {
        dlm.removeAllElements();
        
        for (SignosVitalesFormulario formulario : listaSignosVitalesPaciente) {
            dlm.addElement(formulario.toString());
            System.out.println(formulario);
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel apellidoLabel;
    private javax.swing.JButton buscarPacienteButton;
    private javax.swing.JTextField cedulaTxt;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JList<String> lstFormularios;
    private javax.swing.JLabel nombreLabel;
    private javax.swing.JButton registrarSignosVButton;
    private javax.swing.JLabel tituloLabel;
    // End of variables declaration//GEN-END:variables

    public void setInformation() {
        
    }
    
    private Paciente buscarPaciente(String cedula) {
        for (Paciente paciente : listaPacientes.getPacientes()) {
            if (paciente.getCedula().equals(cedula)) {
                return paciente;
            }
        }
        return null;
    }
    
    private void actualizarPacienteActual(String idSeleccion) {
        listaPacientes = MainScreen.getListaPacientes();
        this.pacienteActual = buscarPaciente(idSeleccion);
        if (pacienteActual != null) {
            if (pacienteActual.getIdMedicoResponsable().equals(MainScreen.getUserID())) {
                registrarSignosVButton.setVisible(true);
                actualizarInfo();
            } else {
                JOptionPane.showMessageDialog(null, "Paciente a cargo de otro médico");
            }
            // Habilita los botones
        } else {
            JOptionPane.showMessageDialog(null, "No encontrado");
        }
    }
    
    private void actualizarInfo() {
        nombreLabel.setText("Nombre: " + pacienteActual.getNombre());
        apellidoLabel.setText("Apellido: " + pacienteActual.getApellido());
    }
    
    private ArrayList<SignosVitalesFormulario> obtenerFormulariosRegistrados() {
        ArrayList<SignosVitalesFormulario> formularios = Main.getFormulariosDataBase();
        return formularios;
    }
    
    private ArrayList<SignosVitalesFormulario> filtrarFormularios(String cedula) {
        ArrayList<SignosVitalesFormulario> formularios = new ArrayList<>();
        if (!listaSignosVitales.isEmpty()) {
            for (SignosVitalesFormulario formulario : listaSignosVitales) {
                if (formulario.getPacienteId().equals(cedula)) {
                    formularios.add(formulario);
                }
            }
        }
        return formularios;
    }
}
