package app.gui.inicio;

import app.logic.users.Paciente;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import javax.swing.JToggleButton;

public class TriajeGui extends javax.swing.JFrame {

    JToggleButton[] botones;
    Paciente paciente;
    int nivelUrgenciaSeleccionado;

    /**
     * Creates new form HistoriaClinica
     *
     * @param paciente
     */
    public TriajeGui(Paciente paciente) {
        initComponents();
        this.paciente = paciente;
        actualizarInfo();
        this.botones = new JToggleButton[]{sinUrgenciaTBtn, urgenciaMenorTBtn, urgenciaTBtn, emergenciaTBtn, resucitacionTBtn};
        this.setLocationRelativeTo(null);
        
        
        // Permite solamente ingresar dígitos en el text field
        alturaTxt.addKeyListener(new KeyAdapter() {
            @Override
            public void keyTyped(KeyEvent e) {
                char c = e.getKeyChar();
                if (!(Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE) || c == KeyEvent.VK_DELETE)) {
                    e.consume();  // ignore the event if it's not an alphabet
                }
            }
        }
        );
        
        pesoTxt.addKeyListener(new KeyAdapter() {
            @Override
            public void keyTyped(KeyEvent e) {
                char c = e.getKeyChar();
                if (!(Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE) || c == KeyEvent.VK_DELETE)) {
                    e.consume();  // ignore the event if it's not an alphabet
                }
            }
        }
        );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator4 = new javax.swing.JSeparator();
        bienvenidaLabel = new javax.swing.JLabel();
        salirBtn = new javax.swing.JButton();
        sexoLbl = new javax.swing.JLabel();
        nombreLbl = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        edadLbl = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        alturaTxt = new javax.swing.JTextField();
        nacionalidadCmb = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        estadoCivilCmb = new javax.swing.JComboBox<>();
        urgenciaMenorTBtn = new javax.swing.JToggleButton();
        urgenciaTBtn = new javax.swing.JToggleButton();
        emergenciaTBtn = new javax.swing.JToggleButton();
        resucitacionTBtn = new javax.swing.JToggleButton();
        sinUrgenciaTBtn = new javax.swing.JToggleButton();
        continuarBtn = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        pesoTxt = new javax.swing.JTextField();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator4.setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 40, 430, 20));

        bienvenidaLabel.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        bienvenidaLabel.setForeground(new java.awt.Color(102, 0, 153));
        bienvenidaLabel.setText("Triaje");
        getContentPane().add(bienvenidaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 10, -1, -1));

        salirBtn.setBackground(new java.awt.Color(204, 204, 204));
        salirBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        salirBtn.setForeground(new java.awt.Color(18, 84, 136));
        salirBtn.setText("X");
        salirBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirBtnActionPerformed(evt);
            }
        });
        getContentPane().add(salirBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 0, 50, -1));

        sexoLbl.setBackground(new java.awt.Color(51, 51, 51));
        sexoLbl.setForeground(new java.awt.Color(51, 51, 51));
        sexoLbl.setText("null");
        getContentPane().add(sexoLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 70, 90, 30));

        nombreLbl.setBackground(new java.awt.Color(51, 51, 51));
        nombreLbl.setForeground(new java.awt.Color(51, 51, 51));
        nombreLbl.setText("null");
        getContentPane().add(nombreLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 210, 30));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 51));
        jLabel3.setText("Sexo:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 70, -1, 30));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 51));
        jLabel4.setText("Nombre:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, 30));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 51, 51));
        jLabel5.setText("Edad:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 70, -1, 30));

        edadLbl.setBackground(new java.awt.Color(51, 51, 51));
        edadLbl.setForeground(new java.awt.Color(51, 51, 51));
        edadLbl.setText("null");
        getContentPane().add(edadLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 70, 80, 30));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 51, 51));
        jLabel6.setText("Estado civil:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 120, -1, 30));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 51, 51));
        jLabel7.setText("Altura en cm:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, 30));

        alturaTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alturaTxtActionPerformed(evt);
            }
        });
        getContentPane().add(alturaTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 210, -1));

        nacionalidadCmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ecuador", "Afganistán", "Albania", "Alemania", "Andorra", "Angola", "Antigua y Barbuda", "Arabia Saudita", "Argelia", "Argentina", "Armenia", "Australia", "Austria", "Azerbaiyán", "Bahamas", "Bangladés", "Barbados", "Baréin", "Bélgica", "Belice", "Benín", "Bielorrusia", "Birmania", "Bolivia", "Bosnia y Herzegovina", "Botsuana", "Brasil", "Brunéi", "Bulgaria", "Burkina Faso", "Burundi", "Bután", "Cabo Verde", "Camboya", "Camerún", "Canadá", "Catar", "Chad", "Chile", "China", "Chipre", "Ciudad del Vaticano", "Colombia", "Comoras", "Corea del Norte", "Corea del Sur", "Costa de Marfil", "Costa Rica", "Croacia", "Cuba", "Dinamarca", "Dominica", "Egipto", "El Salvador", "Emiratos Árabes Unidos", "Eritrea", "Eslovaquia", "Eslovenia", "España", "Estados Unidos", "Estonia", "Etiopía", "Filipinas", "Finlandia", "Fiyi", "Francia", "Gabón", "Gambia", "Georgia", "Ghana", "Granada", "Grecia", "Guatemala", "Guyana", "Guinea", "Guinea ecuatorial", "Guinea-Bisáu", "Haití", "Honduras", "Hungría", "India", "Indonesia", "Irak", "Irán", "Irlanda", "Islandia", "Islas Marshall", "Islas Salomón", "Israel", "Italia", "Jamaica", "Japón", "Jordania", "Kazajistán", "Kenia", "Kirguistán", "Kiribati", "Kuwait", "Laos", "Lesoto", "Letonia", "Líbano", "Liberia", "Libia", "Liechtenstein", "Lituania", "Luxemburgo", "Macedonia del Norte", "Madagascar", "Malasia", "Malaui", "Maldivas", "Malí", "Malta", "Marruecos", "Mauricio", "Mauritania", "México", "Micronesia", "Moldavia", "Mónaco", "Mongolia", "Montenegro", "Mozambique", "Namibia", "Nauru", "Nepal", "Nicaragua", "Níger", "Nigeria", "Noruega", "Nueva Zelanda", "Omán", "Países Bajos", "Pakistán", "Palaos", "Panamá", "Papúa Nueva Guinea", "Paraguay", "Perú", "Polonia", "Portugal", "Reino Unido", "República Centroafricana", "República Checa", "República del Congo", "República Democrática del Congo", "República Dominicana", "Ruanda", "Rumanía", "Rusia", "Samoa", "San Cristóbal y Nieves", "San Marino", "San Vicente y las Granadinas", "Santa Lucía", "Santo Tomé y Príncipe", "Senegal", "Serbia", "Seychelles", "Sierra Leona", "Singapur", "Siria", "Somalia", "Sri Lanka", "Suazilandia", "Sudáfrica", "Sudán", "Sudán del Sur", "Suecia", "Suiza", "Surinam", "Tailandia", "Tanzania", "Tayikistán", "Timor Oriental", "Togo", "Tonga", "Trinidad y Tobago", "Túnez", "Turkmenistán", "Turquía", "Tuvalu", "Ucrania", "Uganda", "Uruguay", "Uzbekistán", "Vanuatu", "Venezuela", "Vietnam", "Yemen", "Yibuti", "Zambia", "Zimbabue" }));
        getContentPane().add(nacionalidadCmb, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, 210, -1));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 51, 51));
        jLabel8.setText("-:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, -1, 30));

        estadoCivilCmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Solter@", "Casad@", "Divorciad@" }));
        getContentPane().add(estadoCivilCmb, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 110, 150, -1));

        urgenciaMenorTBtn.setBackground(new java.awt.Color(0, 161, 0));
        urgenciaMenorTBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        urgenciaMenorTBtn.setForeground(new java.awt.Color(51, 51, 51));
        urgenciaMenorTBtn.setText("Urgencia Menor");
        urgenciaMenorTBtn.setFocusPainted(false);
        urgenciaMenorTBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                urgenciaMenorTBtnActionPerformed(evt);
            }
        });
        getContentPane().add(urgenciaMenorTBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 410, 190, 80));

        urgenciaTBtn.setBackground(new java.awt.Color(254, 220, 0));
        urgenciaTBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        urgenciaTBtn.setForeground(new java.awt.Color(51, 51, 51));
        urgenciaTBtn.setText("Urgencia");
        urgenciaTBtn.setFocusPainted(false);
        urgenciaTBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                urgenciaTBtnActionPerformed(evt);
            }
        });
        getContentPane().add(urgenciaTBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 410, 190, 80));

        emergenciaTBtn.setBackground(new java.awt.Color(255, 121, 0));
        emergenciaTBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        emergenciaTBtn.setForeground(new java.awt.Color(51, 51, 51));
        emergenciaTBtn.setText("Emergencia");
        emergenciaTBtn.setFocusPainted(false);
        emergenciaTBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emergenciaTBtnActionPerformed(evt);
            }
        });
        getContentPane().add(emergenciaTBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 410, 190, 80));

        resucitacionTBtn.setBackground(new java.awt.Color(249, 13, 2));
        resucitacionTBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        resucitacionTBtn.setForeground(new java.awt.Color(51, 51, 51));
        resucitacionTBtn.setText("Resucitación");
        resucitacionTBtn.setFocusPainted(false);
        resucitacionTBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resucitacionTBtnActionPerformed(evt);
            }
        });
        getContentPane().add(resucitacionTBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 410, 190, 80));

        sinUrgenciaTBtn.setBackground(new java.awt.Color(53, 81, 169));
        sinUrgenciaTBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        sinUrgenciaTBtn.setForeground(new java.awt.Color(45, 45, 45));
        sinUrgenciaTBtn.setText("Sin Urgencia");
        sinUrgenciaTBtn.setFocusPainted(false);
        sinUrgenciaTBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sinUrgenciaTBtnActionPerformed(evt);
            }
        });
        getContentPane().add(sinUrgenciaTBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 190, 80));

        continuarBtn.setBackground(new java.awt.Color(18, 84, 136));
        continuarBtn.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        continuarBtn.setForeground(new java.awt.Color(255, 255, 255));
        continuarBtn.setText("Continuar");
        continuarBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        continuarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                continuarBtnActionPerformed(evt);
            }
        });
        getContentPane().add(continuarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 510, 210, 40));

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 51, 51));
        jLabel9.setText("Peso en libras:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, 30));

        pesoTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesoTxtActionPerformed(evt);
            }
        });
        getContentPane().add(pesoTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 210, -1));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/backgroundMain.jpg"))); // NOI18N
        background.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                backgroundKeyPressed(evt);
            }
        });
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backgroundKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_backgroundKeyPressed

    }//GEN-LAST:event_backgroundKeyPressed

    private void salirBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirBtnActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_salirBtnActionPerformed

    private void sinUrgenciaTBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sinUrgenciaTBtnActionPerformed
        seleccionarUrgencia(sinUrgenciaTBtn, 5);
    }//GEN-LAST:event_sinUrgenciaTBtnActionPerformed

    private void urgenciaMenorTBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_urgenciaMenorTBtnActionPerformed
        seleccionarUrgencia(urgenciaMenorTBtn, 4);
    }//GEN-LAST:event_urgenciaMenorTBtnActionPerformed

    private void urgenciaTBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_urgenciaTBtnActionPerformed
        seleccionarUrgencia(urgenciaTBtn, 3);
    }//GEN-LAST:event_urgenciaTBtnActionPerformed

    private void emergenciaTBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emergenciaTBtnActionPerformed
        seleccionarUrgencia(emergenciaTBtn, 2);
    }//GEN-LAST:event_emergenciaTBtnActionPerformed

    private void resucitacionTBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resucitacionTBtnActionPerformed
        seleccionarUrgencia(resucitacionTBtn, 1);
    }//GEN-LAST:event_resucitacionTBtnActionPerformed

    private void continuarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_continuarBtnActionPerformed
        // ---
    }//GEN-LAST:event_continuarBtnActionPerformed

    private void alturaTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alturaTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alturaTxtActionPerformed

    private void pesoTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesoTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pesoTxtActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alturaTxt;
    private javax.swing.JLabel background;
    private javax.swing.JLabel bienvenidaLabel;
    private javax.swing.JButton continuarBtn;
    private javax.swing.JLabel edadLbl;
    private javax.swing.JToggleButton emergenciaTBtn;
    private javax.swing.JComboBox<String> estadoCivilCmb;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JComboBox<String> nacionalidadCmb;
    private javax.swing.JLabel nombreLbl;
    private javax.swing.JTextField pesoTxt;
    private javax.swing.JToggleButton resucitacionTBtn;
    private javax.swing.JButton salirBtn;
    private javax.swing.JLabel sexoLbl;
    private javax.swing.JToggleButton sinUrgenciaTBtn;
    private javax.swing.JToggleButton urgenciaMenorTBtn;
    private javax.swing.JToggleButton urgenciaTBtn;
    // End of variables declaration//GEN-END:variables

    private void seleccionarUrgencia(JToggleButton botonSeleciconado, int nivelUrgencia) {
        if (nivelUrgenciaSeleccionado == 0) {
            activarDesactivarBotones(false);
            botonSeleciconado.setEnabled(true);
            nivelUrgenciaSeleccionado = nivelUrgencia;
        } else {
            activarDesactivarBotones(true);
            nivelUrgenciaSeleccionado = 0;
        }
    }

    private void activarDesactivarBotones(boolean b) {
        for (JToggleButton boton : botones) {
            boton.setEnabled(b);
        }
    }

    private void actualizarInfo() {
        nombreLbl.setText(paciente.getNombre());
        edadLbl.setText("" + paciente.getEdad());
        sexoLbl.setText(paciente.getSexo());
    }
}
