package app.gui.inicio;

import app.logic.SignosVitalesFormulario;
import app.logic.users.Paciente;

public class TriajeGuiForm extends javax.swing.JFrame {

    private final Paciente paciente;
    int id;
    SignosVitalesFormulario formulario;

    /**
     * Creates new form HistoriaClinica
     *
     * @param paciente
     * @param formulario
     * @param id
     */
    public TriajeGuiForm(Paciente paciente, SignosVitalesFormulario formulario) {
        initComponents();
        this.paciente = paciente;
        this.formulario = formulario;
        actualizarInfo();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        aSpn2 = new javax.swing.JSpinner();
        jSeparator4 = new javax.swing.JSeparator();
        bienvenidaLabel = new javax.swing.JLabel();
        sexoLbl = new javax.swing.JLabel();
        grupoSLbl = new javax.swing.JLabel();
        nombreLbl = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        edadLbl = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        prioridadLbl = new javax.swing.JLabel();
        alturaLbl = new javax.swing.JLabel();
        tensionLbl = new javax.swing.JLabel();
        pulsoLbl = new javax.swing.JLabel();
        respiracionLbl = new javax.swing.JLabel();
        pesoLbl = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        fechaLbl = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        apellidoLbl = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        cedulaLbl = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator4.setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, 430, 20));

        bienvenidaLabel.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        bienvenidaLabel.setForeground(new java.awt.Color(102, 0, 153));
        bienvenidaLabel.setText("Triaje");
        getContentPane().add(bienvenidaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, -1, -1));

        sexoLbl.setBackground(new java.awt.Color(51, 51, 51));
        sexoLbl.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        sexoLbl.setForeground(new java.awt.Color(51, 51, 51));
        sexoLbl.setText("null");
        getContentPane().add(sexoLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 80, 90, 30));

        grupoSLbl.setBackground(new java.awt.Color(51, 51, 51));
        grupoSLbl.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        grupoSLbl.setForeground(new java.awt.Color(51, 51, 51));
        grupoSLbl.setText("null");
        getContentPane().add(grupoSLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 280, 110, 30));

        nombreLbl.setBackground(new java.awt.Color(51, 51, 51));
        nombreLbl.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        nombreLbl.setForeground(new java.awt.Color(51, 51, 51));
        nombreLbl.setText("null");
        getContentPane().add(nombreLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 210, 30));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 51));
        jLabel3.setText("Sexo:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 80, -1, 30));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 51));
        jLabel4.setText("Nombre:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, -1, 30));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 51, 51));
        jLabel5.setText("Edad:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 80, -1, 30));

        edadLbl.setBackground(new java.awt.Color(51, 51, 51));
        edadLbl.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        edadLbl.setForeground(new java.awt.Color(51, 51, 51));
        edadLbl.setText("null");
        getContentPane().add(edadLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 80, 80, 30));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 51, 51));
        jLabel7.setText("Altura en cm:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, -1, 30));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 51, 51));
        jLabel8.setText("Prioridad:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 330, -1, 30));

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 51, 51));
        jLabel9.setText("Peso en libras:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, -1, 30));

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 51, 51));
        jLabel10.setText("Tensión arterial:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 230, -1, 30));

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 51, 51));
        jLabel11.setText("Respiración:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 180, -1, 30));

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 51, 51));
        jLabel13.setText("Grupo sanguíneo:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, -1, 30));

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 51, 51));
        jLabel12.setText("Pulso:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 280, -1, 30));

        prioridadLbl.setBackground(new java.awt.Color(51, 51, 51));
        prioridadLbl.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        prioridadLbl.setForeground(new java.awt.Color(51, 51, 51));
        prioridadLbl.setText("null");
        getContentPane().add(prioridadLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 330, 190, 30));

        alturaLbl.setBackground(new java.awt.Color(51, 51, 51));
        alturaLbl.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        alturaLbl.setForeground(new java.awt.Color(51, 51, 51));
        alturaLbl.setText("null");
        getContentPane().add(alturaLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, 110, 30));

        tensionLbl.setBackground(new java.awt.Color(51, 51, 51));
        tensionLbl.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        tensionLbl.setForeground(new java.awt.Color(51, 51, 51));
        tensionLbl.setText("null");
        getContentPane().add(tensionLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 230, 110, 30));

        pulsoLbl.setBackground(new java.awt.Color(51, 51, 51));
        pulsoLbl.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        pulsoLbl.setForeground(new java.awt.Color(51, 51, 51));
        pulsoLbl.setText("null");
        getContentPane().add(pulsoLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 280, 110, 30));

        respiracionLbl.setBackground(new java.awt.Color(51, 51, 51));
        respiracionLbl.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        respiracionLbl.setForeground(new java.awt.Color(51, 51, 51));
        respiracionLbl.setText("null");
        getContentPane().add(respiracionLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 180, 110, 30));

        pesoLbl.setBackground(new java.awt.Color(51, 51, 51));
        pesoLbl.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        pesoLbl.setForeground(new java.awt.Color(51, 51, 51));
        pesoLbl.setText("null");
        getContentPane().add(pesoLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 230, 110, 30));

        jLabel15.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 51, 51));
        jLabel15.setText("Fecha:");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, -1, 30));

        fechaLbl.setBackground(new java.awt.Color(51, 51, 51));
        fechaLbl.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        fechaLbl.setForeground(new java.awt.Color(51, 51, 51));
        fechaLbl.setText("null");
        getContentPane().add(fechaLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, 210, 30));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 51, 51));
        jLabel6.setText("Apellido:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, -1, 30));

        apellidoLbl.setBackground(new java.awt.Color(51, 51, 51));
        apellidoLbl.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        apellidoLbl.setForeground(new java.awt.Color(51, 51, 51));
        apellidoLbl.setText("null");
        getContentPane().add(apellidoLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, 210, 30));

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 51, 51));
        jLabel14.setText("Cédula:");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 110, -1, 30));

        cedulaLbl.setBackground(new java.awt.Color(51, 51, 51));
        cedulaLbl.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        cedulaLbl.setForeground(new java.awt.Color(51, 51, 51));
        cedulaLbl.setText("null");
        getContentPane().add(cedulaLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 110, 140, 30));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/backgroundMain.jpg"))); // NOI18N
        background.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                backgroundKeyPressed(evt);
            }
        });
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backgroundKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_backgroundKeyPressed

    }//GEN-LAST:event_backgroundKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner aSpn2;
    private javax.swing.JLabel alturaLbl;
    private javax.swing.JLabel apellidoLbl;
    private javax.swing.JLabel background;
    private javax.swing.JLabel bienvenidaLabel;
    private javax.swing.JLabel cedulaLbl;
    private javax.swing.JLabel edadLbl;
    private javax.swing.JLabel fechaLbl;
    private javax.swing.JLabel grupoSLbl;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel nombreLbl;
    private javax.swing.JLabel pesoLbl;
    private javax.swing.JLabel prioridadLbl;
    private javax.swing.JLabel pulsoLbl;
    private javax.swing.JLabel respiracionLbl;
    private javax.swing.JLabel sexoLbl;
    private javax.swing.JLabel tensionLbl;
    // End of variables declaration//GEN-END:variables

    private void actualizarInfo() {
        nombreLbl.setText(paciente.getNombre());
        apellidoLbl.setText(paciente.getApellido());
        cedulaLbl.setText(paciente.getCedula());
        edadLbl.setText("" + paciente.getEdad());
        sexoLbl.setText(paciente.getSexo());
        fechaLbl.setText("" + formulario.getFecha().toString());

        alturaLbl.setText("" + formulario.getAltura());
        pesoLbl.setText("" + formulario.getPeso());
        pulsoLbl.setText("" + formulario.getPulso());
        respiracionLbl.setText("" + formulario.getRespiracion());
        tensionLbl.setText("" + formulario.getTension());
        prioridadLbl.setText(formulario.getPrioridadString());
        grupoSLbl.setText(formulario.getGrupoSanguieno());
    }

}
