package app.gui.paciente;

import app.logic.Fecha;
import app.logic.HistoriaClinicaPaciente;
import app.logic.users.Paciente;

public class HistoriaClinicaPanel extends javax.swing.JFrame {

    Paciente paciente;
    HistoriaClinicaPaciente historiaClinica;

    /**
     * Creates new form HistoriaClinica
     *
     * @param paciente
     */
    public HistoriaClinicaPanel(Paciente paciente) {
        initComponents();
        this.paciente = paciente;
        this.historiaClinica = paciente.getHistoriaClinica();
        this.setLocationRelativeTo(null);
        actualizarInfo();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator4 = new javax.swing.JSeparator();
        bienvenidaLabel = new javax.swing.JLabel();
        sexoLbl = new javax.swing.JLabel();
        nombreLbl = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        edadLbl = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        bienvenidaLabel2 = new javax.swing.JLabel();
        bienvenidaLabel1 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cedulaLbl = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        apellidoLbl = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        fechaLbl = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        medicacionLbl = new javax.swing.JLabel();
        padreEstadoLbl = new javax.swing.JLabel();
        madreEstadoLbl = new javax.swing.JLabel();
        otrosLbl = new javax.swing.JLabel();
        consumeTabacolLbl = new javax.swing.JLabel();
        madreAntecedentesLbl = new javax.swing.JLabel();
        ocupacionLbl = new javax.swing.JLabel();
        estadoCivilLbl = new javax.swing.JLabel();
        enfermedadesLbl = new javax.swing.JLabel();
        padreAntecedentesLbl = new javax.swing.JLabel();
        nacionalidadlbl = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        consumeDrogasLbl = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        consumeAlcoholLbl = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(1030, 650));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator4.setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 40, 430, 20));

        bienvenidaLabel.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        bienvenidaLabel.setForeground(new java.awt.Color(102, 0, 153));
        bienvenidaLabel.setText("Historia Clínica");
        getContentPane().add(bienvenidaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 10, -1, -1));

        sexoLbl.setBackground(new java.awt.Color(51, 51, 51));
        sexoLbl.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        sexoLbl.setForeground(new java.awt.Color(51, 51, 51));
        sexoLbl.setText("null");
        getContentPane().add(sexoLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 120, 90, 30));

        nombreLbl.setBackground(new java.awt.Color(51, 51, 51));
        nombreLbl.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        nombreLbl.setForeground(new java.awt.Color(51, 51, 51));
        nombreLbl.setText("null");
        getContentPane().add(nombreLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 90, 30));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 51));
        jLabel3.setText("Sexo:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 120, -1, 30));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 51));
        jLabel4.setText("Nombre:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, 30));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 51, 51));
        jLabel5.setText("Edad:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 70, -1, 30));

        edadLbl.setBackground(new java.awt.Color(51, 51, 51));
        edadLbl.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        edadLbl.setForeground(new java.awt.Color(51, 51, 51));
        edadLbl.setText("null");
        getContentPane().add(edadLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 70, 80, 30));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 51, 51));
        jLabel6.setText("Estado civil:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 170, -1, 30));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 51, 51));
        jLabel7.setText("Ocupación:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, 30));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 51, 51));
        jLabel8.setText("Enfermedades que padece:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 530, -1, 30));

        bienvenidaLabel2.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        bienvenidaLabel2.setForeground(new java.awt.Color(0, 51, 153));
        bienvenidaLabel2.setText("Antecedentes personales");
        getContentPane().add(bienvenidaLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, -1, -1));

        bienvenidaLabel1.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        bienvenidaLabel1.setForeground(new java.awt.Color(0, 51, 153));
        bienvenidaLabel1.setText("Antecedentes familiares");
        getContentPane().add(bienvenidaLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, -1, -1));

        jSeparator5.setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 920, 10));

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 51, 51));
        jLabel10.setText("Padre:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, -1, 30));

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 51, 51));
        jLabel9.setText("Nacionalidad:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, 30));

        cedulaLbl.setBackground(new java.awt.Color(51, 51, 51));
        cedulaLbl.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        cedulaLbl.setForeground(new java.awt.Color(51, 51, 51));
        cedulaLbl.setText("null");
        getContentPane().add(cedulaLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 120, 140, 30));

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 51, 51));
        jLabel14.setText("Cédula:");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 120, -1, 30));

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 51, 51));
        jLabel11.setText("Apellido:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 70, -1, 30));

        apellidoLbl.setBackground(new java.awt.Color(51, 51, 51));
        apellidoLbl.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        apellidoLbl.setForeground(new java.awt.Color(51, 51, 51));
        apellidoLbl.setText("null");
        getContentPane().add(apellidoLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 70, 120, 30));

        jLabel15.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 51, 51));
        jLabel15.setText("Fecha:");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 170, -1, 30));

        fechaLbl.setBackground(new java.awt.Color(51, 51, 51));
        fechaLbl.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        fechaLbl.setForeground(new java.awt.Color(51, 51, 51));
        fechaLbl.setText("null");
        getContentPane().add(fechaLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 170, 150, 30));

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 51, 51));
        jLabel12.setText("Madre:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, -1, 30));

        jSeparator7.setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, 920, 10));

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 51, 51));
        jLabel13.setText("Otros:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, -1, 30));

        jLabel16.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 51, 51));
        jLabel16.setText("- Tabaco");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 460, 90, 30));

        jLabel17.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 51, 51));
        jLabel17.setText("Medicación permanente:");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 580, -1, 30));

        medicacionLbl.setBackground(new java.awt.Color(51, 51, 51));
        medicacionLbl.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        medicacionLbl.setForeground(new java.awt.Color(51, 51, 51));
        medicacionLbl.setText("null");
        getContentPane().add(medicacionLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 580, 670, 30));

        padreEstadoLbl.setBackground(new java.awt.Color(51, 51, 51));
        padreEstadoLbl.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        padreEstadoLbl.setForeground(new java.awt.Color(51, 51, 51));
        padreEstadoLbl.setText("null");
        getContentPane().add(padreEstadoLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 260, 110, 30));

        madreEstadoLbl.setBackground(new java.awt.Color(51, 51, 51));
        madreEstadoLbl.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        madreEstadoLbl.setForeground(new java.awt.Color(51, 51, 51));
        madreEstadoLbl.setText("null");
        getContentPane().add(madreEstadoLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, 110, 30));

        otrosLbl.setBackground(new java.awt.Color(51, 51, 51));
        otrosLbl.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        otrosLbl.setForeground(new java.awt.Color(51, 51, 51));
        otrosLbl.setText("null");
        getContentPane().add(otrosLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 340, 110, 30));

        consumeTabacolLbl.setBackground(new java.awt.Color(51, 51, 51));
        consumeTabacolLbl.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        consumeTabacolLbl.setForeground(new java.awt.Color(51, 51, 51));
        consumeTabacolLbl.setText("null");
        getContentPane().add(consumeTabacolLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 460, 70, 30));

        madreAntecedentesLbl.setBackground(new java.awt.Color(51, 51, 51));
        madreAntecedentesLbl.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        madreAntecedentesLbl.setForeground(new java.awt.Color(51, 51, 51));
        madreAntecedentesLbl.setText("null");
        getContentPane().add(madreAntecedentesLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 300, 710, 30));

        ocupacionLbl.setBackground(new java.awt.Color(51, 51, 51));
        ocupacionLbl.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        ocupacionLbl.setForeground(new java.awt.Color(51, 51, 51));
        ocupacionLbl.setText("null");
        getContentPane().add(ocupacionLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 150, 30));

        estadoCivilLbl.setBackground(new java.awt.Color(51, 51, 51));
        estadoCivilLbl.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        estadoCivilLbl.setForeground(new java.awt.Color(51, 51, 51));
        estadoCivilLbl.setText("null");
        getContentPane().add(estadoCivilLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 170, 150, 30));

        enfermedadesLbl.setBackground(new java.awt.Color(51, 51, 51));
        enfermedadesLbl.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        enfermedadesLbl.setForeground(new java.awt.Color(51, 51, 51));
        enfermedadesLbl.setText("null");
        getContentPane().add(enfermedadesLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 530, 670, 30));

        padreAntecedentesLbl.setBackground(new java.awt.Color(51, 51, 51));
        padreAntecedentesLbl.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        padreAntecedentesLbl.setForeground(new java.awt.Color(51, 51, 51));
        padreAntecedentesLbl.setText("null");
        getContentPane().add(padreAntecedentesLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 260, 710, 30));

        nacionalidadlbl.setBackground(new java.awt.Color(51, 51, 51));
        nacionalidadlbl.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        nacionalidadlbl.setForeground(new java.awt.Color(51, 51, 51));
        nacionalidadlbl.setText("null");
        getContentPane().add(nacionalidadlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 150, 30));

        jLabel18.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 51, 51));
        jLabel18.setText("Consume:");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 430, -1, 30));

        jLabel19.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 51, 51));
        jLabel19.setText("- Drogas");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 490, 90, 30));

        consumeDrogasLbl.setBackground(new java.awt.Color(51, 51, 51));
        consumeDrogasLbl.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        consumeDrogasLbl.setForeground(new java.awt.Color(51, 51, 51));
        consumeDrogasLbl.setText("null");
        getContentPane().add(consumeDrogasLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 490, 70, 30));

        jLabel20.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 51, 51));
        jLabel20.setText("- Alcohol");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 430, 90, 30));

        consumeAlcoholLbl.setBackground(new java.awt.Color(51, 51, 51));
        consumeAlcoholLbl.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        consumeAlcoholLbl.setForeground(new java.awt.Color(51, 51, 51));
        consumeAlcoholLbl.setText("null");
        getContentPane().add(consumeAlcoholLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 430, 70, 30));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/backgroundMain.jpg"))); // NOI18N
        background.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                backgroundKeyPressed(evt);
            }
        });
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backgroundKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_backgroundKeyPressed

    }//GEN-LAST:event_backgroundKeyPressed

    private void actualizarInfo() {
        nombreLbl.setText(paciente.getNombre());
        apellidoLbl.setText(paciente.getApellido());
        cedulaLbl.setText(paciente.getCedula());
        edadLbl.setText("" + paciente.getEdad());
        sexoLbl.setText(paciente.getSexo());
        fechaLbl.setText("" + (new Fecha().toString()));

        // Saca la información de la clase HistoriaClinicaPaciente y la pone en pantalla
        ocupacionLbl.setText(historiaClinica.getOcupacion());
        estadoCivilLbl.setText(historiaClinica.getEstadoCivil());
        nacionalidadlbl.setText(historiaClinica.getNacionalidad());
        padreEstadoLbl.setText(historiaClinica.isPadreFallecido() ? "Fallecido" : "Vivo");
        madreEstadoLbl.setText(historiaClinica.isMadreFallecido() ? "Fallecido" : "Vivo");
        padreAntecedentesLbl.setText(historiaClinica.getAntecedentesPadre());
        madreAntecedentesLbl.setText(historiaClinica.getAntecedentesMadre());
        consumeAlcoholLbl.setText(historiaClinica.isAlcohol() ? "Si" : "No");
        consumeDrogasLbl.setText(historiaClinica.isDrogas() ? "Si" : "No");
        consumeTabacolLbl.setText(historiaClinica.isTabaco() ? "Si" : "No");
        enfermedadesLbl.setText(historiaClinica.getEnfermedades());
        medicacionLbl.setText(historiaClinica.getMedicacion());

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel apellidoLbl;
    private javax.swing.JLabel background;
    private javax.swing.JLabel bienvenidaLabel;
    private javax.swing.JLabel bienvenidaLabel1;
    private javax.swing.JLabel bienvenidaLabel2;
    private javax.swing.JLabel cedulaLbl;
    private javax.swing.JLabel consumeAlcoholLbl;
    private javax.swing.JLabel consumeDrogasLbl;
    private javax.swing.JLabel consumeTabacolLbl;
    private javax.swing.JLabel edadLbl;
    private javax.swing.JLabel enfermedadesLbl;
    private javax.swing.JLabel estadoCivilLbl;
    private javax.swing.JLabel fechaLbl;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JLabel madreAntecedentesLbl;
    private javax.swing.JLabel madreEstadoLbl;
    private javax.swing.JLabel medicacionLbl;
    private javax.swing.JLabel nacionalidadlbl;
    private javax.swing.JLabel nombreLbl;
    private javax.swing.JLabel ocupacionLbl;
    private javax.swing.JLabel otrosLbl;
    private javax.swing.JLabel padreAntecedentesLbl;
    private javax.swing.JLabel padreEstadoLbl;
    private javax.swing.JLabel sexoLbl;
    // End of variables declaration//GEN-END:variables
}
